### ISSUE TITLE
add_header_rows skips when colspan=1

### ISSUE THREAD

**Issue by shabbybanks** [haozhu233/kableExtra#10]
Perhaps I do not understand the point of `add_header_rows`, but I would like to do the following:
```r
require(dplyr)
require(knitr)
require(kableExtra)
nro <- 2
data.frame(x1=rnorm(nro),x2=rnorm(nro),y1=runif(nro)) %>%
  knitr::kable(format='html') %>%
  kableExtra::add_header_above(header=c('x'=2,'y'=1))
```
However, what I get out is:
<table>
 <thead>
  <tr><th style="text-align:center;" colspan="2">x</th><th style="border-bottom:hidden"/></tr><tr>
   <th style="text-align:right;"> x1 </th>
   <th style="text-align:right;"> x2 </th>
   <th style="text-align:right;"> y1 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 0.7999 </td>
   <td style="text-align:right;"> -0.0302 </td>
   <td style="text-align:right;"> 0.3919 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> -1.1490 </td>
   <td style="text-align:right;"> 0.9670 </td>
   <td style="text-align:right;"> 0.1744 </td>
  </tr>
</tbody>
</table>

Where is the `y`? The problem seems to arise in `htmlTable_new_header_generator`, where I see:
```
        if (x[2] == 1 | trimws(x[1]) == "") {
            paste0("<th style=\"border-bottom:hidden\"></th>")
        }
```
Perhaps the `|` should be an `&`?

**Comment by haozhu233** [comment]
Hi, @shabbybanks, I found this bug almost right after `kableExtra` 0.2.1 was released on CRAN and it has been fixed in the current github version. (see https://github.com/haozhu233/kableExtra/blob/master/R/add_header_above.R#L77) 

You can try to install from github for now (`devtools::install_github("haozhu233/kableExtra")`) and the CRAN ver will be updated in 2 weeks.
