### ISSUE TITLE
magic_mirror can't cope with the use of kable option align

### ISSUE THREAD

**Issue by wolfganglederer** [haozhu233/kableExtra#102]
If the kable option `align` is used, it can mess up the result of the `magic_mirror` function

    tab <- kable(head(cars), 
             "latex", 
             align = "p{0.5\\linewidth}p{0.5\\linewidth}")

    magic_mirror(tab)

e.g. the number of columns is not calculated correctly

    $align
    [1] "0.5\\linewidth"
    
    $valign
    [1] "{p{0.5\\linewidth}p{0.5\\linewidth}p{0.5\\linewidth}p"
    
    $ncol
    [1] 13

Thanks for the great package!

**Comment by haozhu233** [comment]
Hi, @wolfganglederer,

Here are two things. 

1. You need to provide a vector of strings as the align argument in `kable`. When you do 
```
> kable(head(cars), 
+          "latex", 
+          align = "p{0.5\\linewidth}p{0.5\\linewidth}")
```
you see
```
\begin{tabular}{p{0.5\linewidth}p{0.5\linewidth}|p{0.5\linewidth}p{0.5\linewidth}}
\hline
...
```
if there is only one element in `align` while your table has 2 columns, `kable` will repeat align twice... It is working because latex is unusually tolerance on that.. In this case, you should use `align = c("p{0.5\\linewidth}", "p{0.5\\linewidth}")`.

2. Right now, `magic_mirror` presumes users follow the function documentation of `kable` and uses only `"c", "l" or "r"` as values of `align`. It is necessary because other parts of this package need to figure out how users intend to align their columns. Although, when you are using `kable` alone, you can choose not to follow the instruction and provide `p{0.5\linewidth}` as values, there is no way for `kableExtra` to figure out whether or not you want to left/right align the columns. At the same time, modifying the "options" can get very difficult (after all, it's regular expressions...). As a result, I don't think this issue can be fixed.
