### ISSUE TITLE
Kable long table title is not coming on the corresponding pages when using collapse_rows option?

### ISSUE THREAD

**Issue by koliii** [haozhu233/kableExtra#112]
Please see this working example:

````{r}
sampleTable <- data.frame(C1 = c(rep("a", 25), rep("b", 25)),
                          C2 = 1:50
                          )

kable(sampleTable,
      format = "latex",
      booktabs = T,
      longtable = T,
      caption = "Sample table") %>%
  collapse_rows(columns = 1)

````

**Comment by haozhu233** [comment]
2 things here:
1. If you are talking about the table caption, just add `kable_styling(latex_options = "repeat_header") %>%` after your `kable` statement will solve this problem

2. If you are talking about the missing "a" in column C1, it's a LaTeX longtable problem and I guess there is nothing I can do. Basically there are 2 ways to insert a `multirow` in LaTeX, one is to do it at the top and count the row span and the other is to insert it in the end and count the row span backwards. `kableExtra` picked the later one to avoid some undesirable behavior of the first one. If you check the direct output of `kable`, the code is there (`\multirow{-25}{*}{\raggedright\arraybackslash a} & 25\\`) but it's not on the page because latex seems to not be able to count things over pages. If you change your data to be  
```
sampleTable <- data.frame(C1 = c(rep("a", 50), rep("b", 25)),
                          C2 = 1:75
                          )
```
you will see that missing `a` coming back again.

**Comment by koliii** [comment]
Thanks @haozhu233 , `kable_styling(latex_options = "repeat_header")` solved this issue.

**Comment by koliii** [comment]
But on adding `%>%
add_footnote(c("Footnote 1", "Have a good day."), notation = "alphabet")`, table is giving error:
` Warning in add_footnote(., c("Footnote 1", "Have a good day."), notation
 = "alphabet"): Notation is set to 'number' and other formats are not
supported.`
