### ISSUE TITLE
duplicated rows in the dataframe with row_spec inserts vphantom argument within the fix_duplicated_rows_latex internal function and mess up the latex format (rmarkdown, kable and kableExtra )

### ISSUE THREAD

**Issue by popomarmotte** [haozhu233/kableExtra#145]
(I reported this error here : [https://stackoverflow.com/questions/49016615/rendering-table-with-conditional-color-in-latex-as-a-pdf-document-with-rownames]

Mikey Harper nicely answered me and explained me the issue.

**Comment by haozhu233** [comment]
Yes, vphantom was there to make every row unique. Clearly, this is a bug. I’ll take a look at it. Thanks for reporting it!

**Comment by steveputman** [comment]
In what may be a related issue with vphantom, its insertion seems to alter **horizontal** spacing in unexpected ways if there is an hphantom present as well. I have a modified formattable::accounting function that appends /hphantom{)} to positive numbers so that the numbers will align in LaTeX. 

For me, the issue seems to be where vphantom is inserted to resolve the duplicate-row issue--it looks like it puts in after the first &. If the vphantom is placed at the end of the line, it seems to resolve the problem.

**Comment by haozhu233** [comment]
@popomarmotte I fixed this issue by putting `vphantom` to the end of the line as @steveputman suggested. Thank you, both!
