### ISSUE TITLE
export latex table (only) to pdf?

### ISSUE THREAD

**Issue by randomgambit** [haozhu233/kableExtra#169]
Hi @haozhu233 , how are you?

Thanks for creating the `wide` format. It is really nice. I have a quick question. Is there a way to use `kableExtra` to only output a latex table to pdf ?

That would be a nice way to use `kableExtra` in Microsoft Word. 

Here is the idea: people want to use the nice formatting features in `kableextra` in Word, which is not possible at the moment. However, one can import a `pdf` in Word. So the only thing one needs to do is to create a `pdf` for each table using `KableExtra`. 

What do you think? How can I do that?

Thanks!1

**Comment by haozhu233** [comment]
Hey @randomgambit :) You can actually do it through `kable_as_image` which will turn latex table to pdf and then to a png (by default) and then use `knitr::include_graphics` to include that in a Word document. However, it seems that some people (including myself after changing to yihui's tinytex instead of a regular texlive) right now are having some troubles with that function. After I used it at my workplace, I also got some feedbacks from my co-worker that they got confused by the fact why they can't edit the table....hmm...😂plus I was quite busy last month so it's still on my to-be-fixed list now (see those open issues...). I mean feel free to check it out and let me know what you get....

**Comment by randomgambit** [comment]
hey @haozhu233 that is really cool! I use the huge miktex distribution so that should not be a problem.

However, running the simple

```
library(knitr)
library(kableExtra)
library(dplyr)
dt <- mtcars[1:5, 1:4]


kable(dt, format = "latex", booktabs = T, caption = "Demo Table") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = T) %>%
  add_header_above(c(" ", "Group 1" = 2, "Group 2[note]" = 2)) %>%
  add_footnote(c("table footnote")) %>% kable_as_image(., filename = 'C:\\Users\\john\\Desktop\\name')
```

gives
```
This is XeTeX, Version 3.14159265-2.6-0.99998 (MiKTeX 2.9.6500 64-bit)
entering extended mode
[1] "C:\\Users\\john\\Desktop\\name.png"
attr(,"class")
[1] "knit_image_paths" "knit_asis"       
Warning message:
running command 'xelatex -interaction=batchmode table_2018-04-15_222810.tex' had status 1 
```

Am I doing something wrong here?

**Comment by randomgambit** [comment]
ha ! it seems to work tho! the file is there! should I worry about this status 1? hey that is pretty cool bro you should mention it on your website!!
