### ISSUE TITLE
align columns on decimal separator

### ISSUE THREAD

**Issue by jmetzel** [haozhu233/kableExtra#174]
Hi,

I'm using kableExtra with knitr in R-Markdown. I prefer to format my tables in R and just print them nicely with kable (i usually use PDF as output device).  Unfortunately, table alignment appears to be limited to left, right, and center (using the "align=" argument of the kable-function). Is there a way to get them to align on the decimal separator (i.e., "."). If there is no easy way, yet, do you think you could implement this in future versions of the package? This would be really helpful. 

Sincerely,
Julian

**Comment by haozhu233** [comment]
Hi, @jmetzel, alignment on decimal separator requires siunitx package but the S column type is very different from others (based on my limited knowledge in LaTeX). It's not like I don't like this feature but I found it's kind of difficult to get it work together with existing column-wise features, such as column width, bold, etc. If you figure out a way to do it, please let me know and I would love to have this feature.

**Comment by p-phillips** [comment]
I agree with Julian - it would be fantastic to have this functionality available through kableExtra.  siunitx makes numeric data very neat.

**Comment by srnnkls** [comment]
You can just provide the S-column (or d whatever you like, if you use dcolumn) spec with `kable`s `align` argument.

**Comment by 1beb** [comment]
@srnnkls Do you happen to have an example of using a s or dcolumn with the align argument? I've tried a bunch of example and it appears to wipe out my defined column.

**Comment by 1beb** [comment]
I sorted this out today after much trial and error. `dcolumn` won't work because it requires the `multicolumn` style headers. I suppose you might be able to play with latex_column_spec but I couldn't find a way to do that. However, with `siunitx` you can achieve the same result. 

https://ctan.dcc.uchile.cl/macros/latex/contrib/siunitx/siunitx.pdf

![image](https://user-images.githubusercontent.com/421859/88249122-0f62ff80-cc69-11ea-9ea5-5ed5f2187856.png)

In your latex preamble you'll need to include (you can do this in the includes section of your Rmd's YAML for example): 
```
\usepackage{siunitx}
\newcolumntype{d}{S[table-format=3.2]}
```

```
kableExtra::kable(
      mtcars[1:10,1:5], "latex", booktabs = TRUE, longtable = TRUE,  align = c("l", rep("d", 4)), linesep = "") %>% kable_styling(full_width=FALSE)
```

One strange thing that I am currently just using gsub to fix is that you need to wrap the column names / headers in `{curly braces}` in order for them to show up appropriately.

![image](https://user-images.githubusercontent.com/421859/88249822-35899f00-cc6b-11ea-8cea-846e2a2c8caa.png)

**Comment by p-phillips** [comment]
Hmm - I can't get this to work.

I get the following error: 

`! Package siunitx Error: Invalid exponent in numerical input 'di'.
`
I can't see anything that explains this when I search.  My MWE is

```
---
header-includes:
    - '\usepackage{siunitx}'
    - '\newcolumntype{d}{S[table-format=3.2]}'
output:
    pdf_document:
        latex_engine: xelatex
---

```{r setup, include=FALSE}
library(kableExtra)
```
 
```{r}
kableExtra::kable(
      mtcars[1:10,1:5], "latex", booktabs = TRUE, longtable = TRUE,  
#      align = c("l", rep("d", 4)), # commenting out this line allows it to compile
      linesep = "") %>% kable_styling(full_width=FALSE)
```

```

**Comment by 1beb** [comment]
Your MWE is missing all the rest of the latex packages required by kableExtra.

**Comment by randomgambit** [comment]
this is GREAT!!!!! @haozhu233 why dont you add this crazy trick on the first page of `kableExtra`? Or at least in the tex manual :D

**Comment by haozhu233** [comment]
@randomgambit Sure thing. I will add that to the manual this weekend. 

@1beb Thanks a lot for this very useful tip!

**Comment by 1beb** [comment]
It should be noted that I was only able to get this working with latex_column_spec = NULL (forcing, the default didn't always guarantee it would work) and this feature is only available on the github version which is why I opened #487

**Comment by haozhu233** [comment]
@1beb I will look into that.

**Comment by haozhu233** [comment]
@1beb I just added your solution to the doc. Thanks again!
