### ISSUE TITLE
column_spec width fails

### ISSUE THREAD

**Issue by petermacp** [haozhu233/kableExtra#23]
Thanks for this awesome package.

Am generating latex tables with knitr::kable and kableExtra as part of a Bookdown project.

I have a two column table, with long text in the second column:

```
library(tidyverse)
library(knitr)
library(kableExtra)

table1 <- tribble(~Term, ~Definition,
                         "Adverse event (AE)", " Any untoward medical occurrence in a subject to whom a medicinal product has been administered including occurrences which are not necessarily caused by or related to that product.",
                         "Adverse reaction (AR)", "Any untoward and unintended response in a subject to an investigational medicinal product, which is related to any dose administered to that subject.",
                         "Unexpected adverse reaction (UAR)", " An adverse reaction the nature and severity of which is not consistent with the information about the medicinal product in question set out in: The SPC for that product (for products with a marketing authorisation); The Investigator's Brochure (IB) relating to the trial in question (for any other investigational product)",
                         "Serious adverse event (SAE); Serious adverse reaction (SAR); Suspected unexpected serious adverse reaction (SUSAR)", "Respectively, any adverse event, adverse reaction or unexpected adverse reaction that: results in death; is life-threatening; requires hospitalisation or prolongation of existing hospitalisation; results in persistent or significant disability or incapacity; consists of a congenital anomaly or birth defect; other important medical event(s)"
)
```

When I try to specify the width of the second column, it fails.

```
knitr::kable(table1, caption = "Terms and definitions for adverse events", booktabs=TRUE) %>%
  kable_styling(full_width=F, latex_options = "scale_down") %>%
  column_spec(column = 2, width = "30em")
```

with the following message:

```
! Use of \@array doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.1133 \end{tabular}}
```

Very grateful for any suggestions for resolving.

**Comment by haozhu233** [comment]
Hi, @petermacp, I tried to reproduce this bug in `output: bookdown::pdf_document2:` with both CRAN and github version but the document was rendered successfully. Could you try to update your bookdown and see if it helps?

From the bug itself, it seems like the latex `array` package was not loaded by default. it makes me wondering if your bookdown version is up to date.

Another possible source of error is that you probably didn't load `kableExtra` in your actual document and used things like `kableExtra::column_spec`. In 0.3.0, I made a change that centralized all latex package loading attempts when package is loaded but it seems like a bad idea because people (including me) use things like `kableExtra::column_spec` occasionally.

**Comment by viking** [comment]
I'm experiencing this same problem using knitr. Here's my markdown file:

    ---
    output: 
      pdf_document:
              fig_width: 6
              fig_height: 9
              fig_caption: true
    ---
    ```{r foo, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
    kable(data.frame(a = 1:10), format = "latex") %>% column_spec(column = 1, width = "2in")
    ```

And my R program:

    library(knitr)
    library(kableExtra)
    library(magrittr)
    rmarkdown::render("foo.Rmd", output_file="foo.pdf")
