### ISSUE TITLE
R version for kableExtra 0.3.0

### ISSUE THREAD

**Issue by natgoodman** [haozhu233/kableExtra#27]
Greetings. Does kableExtra 0.3.0 really need R >= 3.2.3 or is this an oopsie?

Thanks,
Nat Goodman

**Comment by haozhu233** [comment]
Ops lol

Well, in fact, I increased the version requirement of R since there was a unknown bug reported by a user in #17. Now I feel like that decision is a little rational and inappropriate. I just checked the R version requirement for all my dependencies and found that knitr has the highest R version dependency (>= 3.1.0). I will make some changes accordingly. 

Thanks for reporting!

**Comment by natgoodman** [comment]
Thanks!

All the best,
Nat
