### ISSUE TITLE
kable_styling seems to break fenced divs in pandoc (when converting to html)

### ISSUE THREAD

**Issue by benwhalley** [haozhu233/kableExtra#276]
**Describe the bug**
kable_styling seems to break fenced divs in pandoc (when converting to html). See the example below.

**To Reproduce**

https://gist.github.com/9e935a6accf3171eb92d578ed3835338

**Comment by MikeInBelize** [comment]
I believe I may be having the same, or a similar problem (I'm not sure as I'm a complete beginner with css/js). I posted about this over on the rstudio community forum (which unfortunately I didn't get any responses to): [see here for a description](https://community.rstudio.com/t/kableextra-disabling-javascript-in-bookdown-rmarkdown-documents/15467).

But I've since narrowed it down to `kable_styling()` causing the problem. The following code works as expected:

```
<div class="fold s">
'''{r, eval=FALSE}
# Some code I don't want to show but to be accessible for interested readers...
head(mtcars)
mtcars %>%
  group_by(mpg) %>%
  summarise(nonsense = mean(cyl))
'''
</div>


'''{r}
library(tidyverse)
library(kableExtra)
dt <- mtcars[1:5, 1:6]
dt %>%
  kable()
'''
```
but as soon as I add `%>% kable_styling` after `kable()` my code breaks and the show/hide code doesn't work (please note i replaced ` with ' in my code examples in order to post here).

**Comment by haozhu233** [comment]
Hi, @benwhalley, sorry for the delay. I guess this is more like an rmarkdown or knitr issue. I removed the kableExtra part from your example and it didn't work either. In this case, you might have to use real html code to do the wrapping. 

````
---
title: Quantifying uncertainty
output: html_document
---

```{r}
library(tidyverse)
```



<div class="a">

The wraper div with class `.a` breaks

```{r}
mtcars %>% head() %>% knitr::kable(format="html")
```

</div>
````
