### ISSUE TITLE
Warning message "This document format requires a nonempty <title> element"

### ISSUE THREAD

**Issue by yiqinfu** [haozhu233/kableExtra#310]
Knitting a simple table now returns a warning message (and the resulting html has `<!DOCTYPE html>` in it):

Warning message:
```
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'table1'
```

Code:
```{r}
library(knitr)
library(kableExtra)
library(tidyverse)

kable(mtcars) %>%
  kable_styling() %>%
  save_kable(file = "table1.html", self_contained = T)
````

**Comment by haozhu233** [comment]
Hi, @yiqinfu, I couldn't solve the warning because it was generated by pandoc. We seem to hit a bug in pandoc that even if I put in a <title> it won't work. [This issue](https://github.com/jgm/pandoc/issues/4048) mentions that it might be solved by providing `title` as pandoc options. However this is not possible with the current `rmarkdown::pandoc_self_contained_html`

I fixed the `<!DOCTYPE html>` though. :P

**Comment by over-soul** [comment]
My resulting HTML file also has <!DOCTYPE html> in it at the top.

**Comment by S-UP** [comment]
Just realized my HTML files also show the <!DOCTYPE html> on top. Was not an issue in the past. How to get rid of them? I have updated all packages.

**Comment by MarkErik** [comment]
I am also seeing <!DOCTYPE html> at the top of my html files.

Some example code: 

```
iris[1:10, ] %>%
  mutate_if(is.numeric, function(x) {
    cell_spec(x, bold = T, 
              color = spec_color(x, end = 0.9),
              font_size = spec_font_size(x))
  }) %>%
  mutate(Species = cell_spec(
    Species, color = "white", bold = T,
    background = spec_color(1:10, end = 0.9, option = "A", direction = -1)
  )) %>%
  kable(escape = F, align = "c") %>%
  kable_styling(c("striped", "condensed"), full_width = F)%>%
  save_kable(file = "table1.html", self_contained = T)
```

**Comment by aderzelle** [comment]
Hello,

having the same issue, it works for some of my tables, not for others. Did any of you find a solution to this? 
Thanks

**Comment by r2evans** [comment]
@haozhu233, I wonder if this issue should be reopened to document/indicate one of two actions:

1. Copy `rmarkdown::pandoc_self_contained_html` into a `kabelExtra` version of the function that adds a title (this works in some hasty testing, with caveats); or
2. Update/remove the documentation and function options, since it is currently unusable (at least some/most of the time ... it is always unusable so far for me, but @aderzelle's comment suggests otherwise.

I think the first is not hard to do, though it carries a *little* risk: `rmarkdown:::write_utf8` is not exported (though I find it hard to believe that it would go away).

**Comment by haozhu233** [comment]
Reopening in case I lost the track

**Comment by r2evans** [comment]
I've tested this code and it stops the warning:

```r
    selfcontained <- function(input, output) {
      input <- normalizePath(input)
      if (!file.exists(output)) 
        file.create(output)
      output <- normalizePath(output)
      template <- tempfile(fileext = ".html")
      on.exit(unlink(template), add = TRUE)
      rmarkdown:::write_utf8("$body$", template)
      from <- if (rmarkdown::pandoc_available("1.17")) "markdown_strict" else "markdown"
      rmarkdown::pandoc_convert(input = input, from = from, output = output, 
                                options = c("--metadata", 'pagetitle=""', "--self-contained",
                                            "--template", template))
      invisible(output)
    }

    if (self_contained) {
      # Generate a random temp lib directory. The sub is to remove any back or forward slash at the beginning of the temp_dir
      temp_dir <- sub(pattern = '^[\\\\/]{1,2}', replacement = '', tempfile(pattern = 'lib', tmpdir = '' , fileext = ''))
      htmltools::save_html(html_result, file = file, libdir = temp_dir)
      #remove_html_doc(file)
      selfcontained(file, file)
      unlink(file.path(dirname(file), temp_dir), recursive = TRUE)
    } else {
      # Simply use the htmltools::save_html to write out the files. Dependencies go to the standard lib folder
      htmltools::save_html(html_result, file = file)
    }
```

Interesting enough:

- I *still* see `<!DOCTYPE html>` at the top of the page, I can't figure out why it's there
- even if I set it different with `c("--metadata", 'pagetitle="HELLO THERE!"', ...)`, I don't see the pagetitle in the rendered document; while this might (??) be a bug in `pandoc`, the point is that if we use this function and force-add some page title, it has no effect on the output (other than to silence the warning from `pandoc`)

The risk with doing something like this is (to me) obvious and non-trivial: if/when `rmarkdown` updates this function and/or `pandoc_convert`, then we'll need to update this internal function as well. Looking at that function's history (https://github.com/rstudio/rmarkdown/blame/3d73eae0523f309e13ecd650488ebf600ecccf36/R/pandoc.R#L404), the last few changes:

- (Dec 2018) changed from `writeLines` to `write_utf8`
- (Oct 2017) remove tempfile template
- (May 2016) several other changes

it doesn't look like this function has changed its API at all, so appears relatively stable. Since Rstudio tends towards semantic versioning, we could always insert a simple check, such as

```r
    selfcontained <- function(input, output) {
      if (packageVersion("rmarkdown") >= "3.0") {
        warning("this version of 'kableExtra::save_kable_html' is not tested against 'rmarkdown' version 3 or later")
      }
      ...
    }
```

So even though it is a little sketchy, it appears to be at least *safe-ish sketchy*.

@haozhu233  thoughts?

**Comment by haozhu233** [comment]
@r2evans I don't see any issue at all. `pandoc_convert` is an exported function and is the foundation of many rmarkdown functions. Based on my understanding to yihui's coding standards, if he releases something, he will try his best to keep it stable. 

When I dig into this issue tonight, I also find that this self-contained approach is a little bit hacky. If you do it using the regular pandoc conversion, either through `pandoc_convert` or the command line with input html and output html, you will, in fact, lose all your css and js. What they did here, is to put all these html head stuff inside the body of the new html after base64 encoding. I didn't even know you can do that with css. 😂

Anyway, I fixed this issue in the last commit. I simply removed the `<!DOCTYPE html>` in the localized `save_HTML` function (I added that for a different reason, see #499) and the problem is gone. ;)
