### ISSUE TITLE
group_rows() breaks after dplyr 0.8.0 update

### ISSUE THREAD

**Issue by b1azk0** [haozhu233/kableExtra#344]
**Describe the bug**
Adding a `group_rows()` parameter no longer works.
I used it as:
```
df %>%
  select(cn1:is4, hab1:hab4, ih1, ih2) %>% describe(ranges = F) %>%
  kable(digits = 2, booktabs = T) %>%
  kable_styling(latex_options = c("repeat_header"),
  position = "center") %>%
  group_rows("Collective Narcissism", 1, 5) %>%
  group_rows("In-group Satisfaction", 6, 9) %>%
  group_rows("Intergroup Hostility", 14, 15) %>%
  group_rows("Hostile Attribution Bias", 10, 13) %>%
  footnote(general = "Raw item scores are reported", threeparttable=T)
```
And had no problem in getting the following output:

![image](https://user-images.githubusercontent.com/22635132/52944854-b3f45a00-3370-11e9-9157-6fdbf8debd56.png)

Currently running same code gives an error:

```
Error in group_rows(., "Collective Narcissism", 1, 5) : 
  unused arguments ("Collective Narcissism", 1, 5)
```

**To Reproduce**
I can reproduce the same error by using exemplary code from `?group_rows()` 

```
> x <- knitr::kable(head(mtcars), "html")
> # Put Row 2 to Row 5 into a Group and label it as "Group A"
> group_rows(x, "Group A", 2, 5)
Error in group_rows(x, "Group A", 2, 5) : 
  unused arguments ("Group A", 2, 5)
> 
```

**Comment by b1azk0** [comment]
Apparently `dplyr` uses same function name.
I had to rearrange libraries loading sequence so that `kableExtra` mask this command:

```
> library(kableExtra)

Attaching package: ‘kableExtra’

The following object is masked from ‘package:dplyr’:

    group_rows
```

**Comment by haozhu233** [comment]
Yeah, I personally also have a tons of breaking codes to fix at work. :( I mentioned this to the dplyr team on twitter but they told me this feature has been in the dev version since May and they have made an announcement in December... https://twitter.com/romain_francois/status/1096462503658303489 

It is very unfortunate this happened and it seems that none of the dplyr main developer and testers have used this package before.... For now, you can use the `conflicted` package as Romain suggested. Also, as I said, I will add an alias to the `group_rows` function. 

You can also think about start an issue on dplyr. The `dplyr::group_rows` is sort of a trivial function and the main audience I think is for tidyverse developer. I'm not sure if there are more people than just me mentioning this, they might want to change this....
