### ISSUE TITLE
Ability to create borders for columns (similar to align in xtable)

### ISSUE THREAD

**Issue by Courvoisier13** [haozhu233/kableExtra#35]
In xtable we can use align to add column borders with a | pipe:

`xtable(latex_xtable_outliers, align = "rrll|llr|r")`

Regardless of the alignment, (https://github.com/haozhu233/kableExtra/issues/26), I think the border is very important and currently missing from kable and pander.

I know kableExtra does something similar with the  `add_header_above`, but that forces us to write a column group name, and for some reason (html related) I don't always get the borders visible. 
Also if I leave a blank name in `add_header_above`, it does not do the grouping anymore.

Is what I am asking for even doable, given that it's html?

Thanks

**Comment by haozhu233** [comment]
@Courvoisier13 Sorry for the delay. I have been traveling in the past few days. 

Hmm, first of all, `kable` does support border, but this feature is LaTeX only.

```
kable(mtcars[1:10, 1:2], format = "latex",  align =c("|c", "l"), booktabs = T) %>% 
kable_styling(latex_options =c("striped", "hold_position"))
```

For HTML, things are getting a little complicated due to the various HTML templates. Some templates show borders by default while others choose not to display the borders. Hmm, I think what I can do here is to add a few extra HTML only options to `add_header_above`. I will post my idea here later once I come up with a good design.

**Comment by Courvoisier13** [comment]
yes, that is true. I noticed that the border depends on the template. I didnt know we could add a pipe in the align in kable. I can play around with this see what i get.

**Comment by Courvoisier13** [comment]
I checked again. You are right. the pipe works on in Latex. otherwise it gives an error.

**Comment by haozhu233** [comment]
Hi, @Courvoisier13 

I added two new options to `column_spec` today, namely `border_left/`border_right`. So basically you can do things like

```
column_spec(..., border_left = T) 
```

to add a column to the right. 

For HTML, the value can also be a character string for the CSS.

**Comment by vrybkin** [comment]
Hi @haozhu233, sorry to bug you again. I'm using 0.8.0 and I'm not sure the border_left/border_right string features work for me. For example, column_spec(..., border_left = "lightgrey") does not work, even though setting the argument to TRUE does. I've used HEX codes as well and it does not seem to be working. However, column_spec(..., background = "lightgrey") does work.

The column_spec function is very handy, thanks!

**Comment by vrybkin** [comment]
As a note to others potentially reading this, a simple work around solution is:
`column_spec(..., extra_css = "border-right:2px solid lightgrey;")` for example.

**Comment by iago-pssjd** [comment]
Hi @haozhu233 ,
I am using `add_header_above` , `column_spec(..., border_left = T)`, and also `align =c("|c", "l")` instructions, since I want a pdf document, but the vertical lines only cover data output and column names, but not the added header above. Further the vertical lines for data and for column names are discontinuous.
I attach the image:

![testplot](https://user-images.githubusercontent.com/40892925/59596942-f77d8b80-90f8-11e9-8496-e91400d8e3f0.png)

How can I do?

Thank you!

**Comment by dtdibaba** [comment]
Hi @haozhu233 
Can you add an option to add solid and broken lines to the header and bottom of last row in html? Now, it does not allow to edit the default lines as far as I tried.

**Comment by obrienmr** [comment]
Hi @iago-pssjd 

Did you ever find a resolution to the problem of the discontinuous lines in a pdf document?  I am also producing a pdf using tinytex and am having the same issue.

Cheers!

> Hi @haozhu233 ,
> I am using `add_header_above` , `column_spec(..., border_left = T)`, and also `align = c('|l','|l','c','|l','c|')` instructions, since I want a pdf document, but the vertical lines only cover data output and column names, but not the added header above. Further the vertical lines for data and for column names are discontinuous.
> I attach the image:
> 
> ![testplot](https://user-images.githubusercontent.com/40892925/59596942-f77d8b80-90f8-11e9-8496-e91400d8e3f0.png)
> 
> How can I do to get the vertical lines along all the table?
> 
> Thank you!

**Comment by iago-pssjd** [comment]
No, I didn't, but I didn't try it anymore.

**Comment by makika82** [comment]
I'm also asking for continuous vertical lines, thank you =)

**Comment by AhmedKhaled945** [comment]
Hello everyone, wanted to ask about a way to increase border thickness in latex output (knitting to PDF in RMD)
how can i do it, because i see a comment but it is css code

**Comment by jarbet** [comment]
> I'm also asking for continuous vertical lines, thank you =)

I'm also curious about this, as often the borderline has little breaks/spaces in it when knitting to PDF.
