### ISSUE TITLE
Global kable_styling() definition

### ISSUE THREAD

**Issue by serghiou** [haozhu233/kableExtra#374]
Hi there! 

Thank you so much for an amazing package!

I find that I use the same options for `kable_styling()` across my HTML/LaTeX documents, which made me wonder whether it is possible to set global options for `kable_styling()` and then have it run automatically every time we attempt to print a data frame.

For example, instead of having to every time type,

```{r}
df %>%
  kable() %>% 
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

it would be great to simply type

```{r}
df
```

and have it printed as the first one, or at least be able to type

```{r}
df %>%
  kable() %>% 
  kable_styling()
```

and have it printed as the first one. Even though a slight workaround is to include `df_print: kable` in the preamble, this does not incorporate the custom styling provided by kableExtra.

Thanks a lot in advance!

**Comment by haozhu233** [comment]
Hi, @serghiou, having global options is certainly a good idea. In fact I did put in a few global options there, such as 
https://github.com/haozhu233/kableExtra/blob/f8207137507be2b8314628d7ddd93bf86ef2ae88/R/kable_styling.R#L100

However, I personally found those kind of settings are hard to remember and use because there are no code auto-complete for these in RStudio. When I use this package by myself. I usually write a `sable` function, which stands for simple kable, at the very beginning. The contents of this function depend on what I actually need but here is an example

```
sable <- function(x, escape = T) {
  kable(x, escape = escape) %>%
    kable_styling("striped", full_width = T)
}
```

**Comment by serghiou** [comment]
Hi @haozhu233, 

Thanks for your reply! 

Yes, I also  tried the auto-complete with no success and have also defined a similar function. However, for me personally, having global options is convenient because I have my own local package of R Markdown templates (just made this public: [serghiou/serghiouTemplates](https://github.com/serghiou/serghiouTemplates)), so as soon as I update my package with the global options I'll immediately have them predefined for all future R Markdown templates I use. It's just that it would be great to avoid having any styling function after the original code.

The global options you pointed out look great :)

Thanks for a great package again!
