### ISSUE TITLE
`options(kableExtra.html.bsTable = T)` seems to change column size

### ISSUE THREAD

**Issue by ericpgreen** [haozhu233/kableExtra#381]
I am using the tufte-inspired [msmbstyle](https://github.com/grimbough/msmbstyle) bookdown template, and I was having problems getting my tables to appear with row highlighting. I stumbled upon your [great example](https://haozhu233.github.io/kableExtra/bookdown/use-bootstrap-tables-in-gitbooks-epub.html) of how to integrate kableExtra into bookdown, and I learned to set `options(kableExtra.html.bsTable = T)`. 

This worked for the table styling, but it seems to shrink the column size and affect the position of column content.

![Untitled-2](https://user-images.githubusercontent.com/546433/57553531-c8773b80-733c-11e9-8474-ef7dce0a7664.jpg)

If I remove `options(kableExtra.html.bsTable = T)`, the column width goes back to normal but there is no table styling of course.

![Untitled-1](https://user-images.githubusercontent.com/546433/57553583-f65c8000-733c-11e9-8f80-7142f3920327.jpg)

Is there a way to turn on `options(kableExtra.html.bsTable = T)` for table styling but keep column widths stable?

**Comment by haozhu233** [comment]
Hey Eric, this is the reason why I set the default of `kableExtra.html.bsTable` as off. Basically it will load the table part of bootstrap for you. Since css takes effect by "overwriting", it may conflict with certain themes. In this case, without the actual html file, it's kind of hard for me to say what went wrong. I think you can check this unminimized css file below and try to diagnose by yourself. It doesn't look like there are any css that can affect column width though. 

https://gist.github.com/haozhu233/36ed311217c6dab8434f26ce23a1f2df

Since your bookdown css already has some styles for tables. I think a better idea here would be adding some customized css for this template instead of load bootstrap table css. The bootstrap css included in this package is more general and included many features that you are not using and actually cause the trouble.

**Comment by ericpgreen** [comment]
Thanks for the quick reply, @haozhu233. And for creating such a great package. 

It appears that turning off `bsTable` as you suggest and adding the following to my css file does the trick:

```
.table-striped>tbody>tr:nth-of-type(odd) {
    background-color: #f9f9f9
}
```
