### ISSUE TITLE
Excessive number of dependency packages

### ISSUE THREAD

**Issue by nextpagesoft** [haozhu233/kableExtra#391]
First of all, thanks for this package. It's really useful and I appreciate your time spent on developing it. However, when using it I've noticed that it brings a lot of other R packages as dependencies. In fact it has 65 imported packages:
```r
 [1] "kableExtra"   "knitr"        "magrittr"     "stringr"      "xml2"        
 [6] "rvest"        "rmarkdown"    "readr"        "scales"       "viridisLite" 
[11] "htmltools"    "rstudioapi"   "glue"         "webshot"      "digest"      
[16] "Rcpp"         "evaluate"     "highr"        "markdown"     "yaml"        
[21] "xfun"         "tibble"       "hms"          "R6"           "clipr"       
[26] "crayon"       "BH"           "base64enc"    "jsonlite"     "mime"        
[31] "tinytex"      "httr"         "selectr"      "labeling"     "munsell"     
[36] "RColorBrewer" "stringi"      "callr"        "processx"     "pkgconfig"   
[41] "rlang"        "curl"         "openssl"      "colorspace"   "cli"         
[46] "fansi"        "pillar"       "assertthat"   "askpass"      "utf8"        
[51] "vctrs"        "ps"           "sys"          "backports"    "zeallot"     
[56] "praise"       "withr"        "htmlwidgets"  "tidyselect"   "plogr"       
[61] "purrr"        "testthat"     "magick"       "formattable"  "dplyr" 
```

This seems really excessive and I would say that most of if it is not really needed as they are dragged in by your main dependencies, but `kableExtra` may never need them. Have you ever considered reviewing this list and move some of the main dependencies into `Suggests`, rather than `Imports` and provide some functionality optionally?

**Comment by jangorecki** [comment]
Agree, additionally installation is terribly slow. It discourages the use of it in production environment, where more dependencies is a higher risk of failure.

**Comment by wibeasley** [comment]
I don't have an opinion about the threshold of "excessive".  But here's some code to compare what is added on top of rmarkdown, xml2, and knitr.

```r
library(rmarkdown)
library(knitr)
library(xml2)
loaded_before <- names(sessionInfo()$loadedOnly)

library(kableExtra)
loaded_after <- names(sessionInfo()$loadedOnly)

setdiff(loaded_after, loaded_before)
```

result:
```
 [1] "rstudioapi"  "magrittr"    "hms"         "munsell"     "rvest"      
 [6] "viridisLite" "colorspace"  "R6"          "stringr"     "httr"       
[11] "webshot"     "lifecycle"   "tibble"      "crayon"      "readr"      
[16] "vctrs"       "glue"        "stringi"     "pillar"      "scales"     
[21] "pkgconfig" 
```
```r
installed_before <-
  pak::lib_status() %>% 
  dplyr::filter(package %in% c("rmarkdown", "knitr", "xml2")) %>% 
  dplyr::select(deps) %>% 
  tidyr::unnest_longer(deps) %>% 
  dplyr::distinct(deps$ref)

installed_after <-
  pak::lib_status() %>% 
  dplyr::filter(package %in% c("kableExtra")) %>% 
  dplyr::select(deps) %>% 
  tidyr::unnest_longer(deps) %>% 
  dplyr::distinct(deps$ref)

dplyr::anti_join(installed_after, installed_before)
```
result:
```
# A tibble: 10 x 1
   `deps$ref` 
   <chr>      
 1 formattable
 2 dplyr      
 3 rvest      
 4 readr      
 5 scales     
 6 viridisLite
 7 stats      
 8 grDevices  
 9 rstudioapi 
10 glue 
```

**Comment by haozhu233** [comment]
@nextpagesoft @jangorecki A few things here: 
1. After a careful review, I replaced some functions from readr with some alternatives so I took away readr from Imports dependencies. Also I updated the doc. Instead of using dplyr's mutate, I wrote the code in base R and put the dplyr version in comments. I guess now it's 2020, there is no need to advocate for dplyr any more. Having done that, it will speed up the installation a lot. Based on my experience on administrating a linux machine, the most time consuming piece is the installation of `BH` which is brought in by `dplyr` and `readr`. 

2. In terms of dplyr, this package doesn't need dplyr but I used it to build the vignette so it was listed in Suggest. The reason why I chose to remove `dplyr` this time is that by default, R will also install packages listed in `Suggest`. The documentation of `install.packages` says

> TRUE means to use c("Depends", "Imports", "LinkingTo", "Suggests") for pkgs and c("Depends", "Imports", "LinkingTo") for added dependencies: this installs all the packages needed to run pkgs, their examples, tests and vignettes (if the package author specified them correctly).

3. The entire tidyverse is a big chunk of modern R programming. Even if I removed these dependencies here, you will likely need to install them for some other reasons. I think in most cases it won't discourage use in production. Of course, if for you, this package is more important than dplyr, I will take that as a praise. 😛


@wibeasley Thanks as always for your support! :)

**Comment by wibeasley** [comment]
@haozhu233, I like your 3rd point.  

FYI, [dplyr](https://cran.r-project.org/web/packages/dplyr/) got skinnier it the [recent 1.0.0 release](https://cran.r-project.org/web/packages/dplyr/news/news.html).

> dplyr dropped its two heaviest dependencies: Rcpp and BH. This should make it considerably easier and faster to build from source.

However [readr](https://cran.r-project.org/web/packages/readr/) is still linking to Rcpp & BH.   But they may be trying to slim down readr in the future.  [vroom](https://vroom.r-lib.org/) replaced Rcpp with cpp11, and [its code base apparently will influence readr](https://github.com/tidyverse/tidyverse.org/pull/375#issuecomment-564781603).

**Comment by haozhu233** [comment]
@wibeasley That is really good to know! It always takes so much time to build BH on linux. Thanks for the tip!

Anyway, I wasn't using readr for any fancy things in this package. It makes sense to replace it with alternatives in stringr
