### ISSUE TITLE
issue with pipe operator

### ISSUE THREAD

**Issue by rumbach31** [haozhu233/kableExtra#409]
When I try to run the following code
x<-knitr::kable(head(mtcars), format="latex") %>%
kableExtra::add_footnote(x, c("footnote 1", "footnote 2"), notation = "symbol")
 just in the console I get this error
Error in !threeparttable : invalid argument type

When I try to knit that same code as part of a larger document (which works fine when I don't include this code), I get this error 
Error in knits::kable(head(mtcars), format="latex") %>% kableExtra::add_footnote(x, c("footnote 1", "footnote 2"), notation = "symbol")...can't find function %>%

**Comment by joshpk** [comment]
This is probably more appropriately posted on [stackoverflow](https://stackoverflow.com/)

Saying that, your first error is because you are refering to an object in your pipe that is not yet created. And your second error will be because the library `dplyr` is not loaded. This works:

````
---
title: "R Notebook"
output:
  pdf_document: default
---

```{r}
library(dplyr)
library(kableExtra)

head(mtcars) %>% 
  kable(format="latex") %>%
  add_footnote(c("footnote 1", "footnote 2"), notation = "symbol")
```
````

**Comment by jangorecki** [comment]
It would be useful to provide a pipe-less documentation as well, for many users it is still more readable.

**Comment by haozhu233** [comment]
@rumbach31 kableExtra also comes with a copy of the pipe operator but you need to load the package. 

@joshpk Thanks a lot for helping! :)

@jangorecki Yeah, I understand that pipe operator may look confusing for many non-R users.. I wish I could provide more documentation but I don't have enough time. I just added a few sentences to the current documentation and described what the pipe symbols mean. I hope it helps.
