### ISSUE TITLE
Add the third parameter for wraptable using position = "float_right"

### ISSUE THREAD

**Issue by caimiao0714** [haozhu233/kableExtra#414]
Hi Hao,

I wonder if there is a way to add a parameter for `wraptable` using `position = "float_right"`. Here is my example code and output.

```
fread("data/12_driver.csv") %>% 
  dplyr::slice(1:5) %>% 
  kable("latex", align = "c", 
      booktab = TRUE, linesep = "", 
      caption = "drivers") %>% 
  kable_styling(position = "float_right")
```

The output is:
```
\begin{wraptable}{r}{0pt}[t]

\caption{\label{tab:}drivers}
\centering
\begin{tabular}{cc}
\toprule
driver & age\\
\midrule
canj1 & 46\\
farj7 & 54\\
gres0 & 55\\
hunt & 48\\
kell0 & 51\\
\bottomrule
\end{tabular}
\end{wraptable}
```

Is there a way to change the third parameter from `{0pt}` to another value such as `{5cm}`? I don't see it in the official document or stackoverflow.

Thank you!

**Comment by haozhu233** [comment]
@caimiao0714 I just added a `wraptable_width` option to `kable_styling`. The documentation for `wrapfig` also recommends setting the width manually because the automated `0pt` was made based on estimation and can be wrong. 
https://github.com/haozhu233/kableExtra/commit/f2f420290e8343208933de5af7f4edc8aa0d8bc7
