### ISSUE TITLE
Failure of text wrap around right-floating table

### ISSUE THREAD

**Issue by howardm** [haozhu233/kableExtra#438]
Hi,

Can you see the reason why the text wrap is not working for the following ? I'm using it in a Distill article .Rmd file.

Code:
___
![Screen Shot 2019-11-16 at 10 52 30 AM](https://user-images.githubusercontent.com/6101226/68997079-9f8db100-085f-11ea-8619-4e4b4185c8ad.jpg)
___

Lorem ipsum dolor sit amet,   [etc]

The result:

___

![Screen Shot 2019-11-16 at 10 52 00 AM](https://user-images.githubusercontent.com/6101226/68997084-b46a4480-085f-11ea-80d4-5ae23eb13d3e.jpg)
___

Thanks!

Howard

**Comment by haozhu233** [comment]
hi Howard, this is because Distill put the R output in a `<div>`. I think they add this step to offer some extra control over the styles but it makes the floating thing stop working. Unfortunately I don't think it's possible to fix that...

<img width="316" alt="Screen Shot 2019-11-16 at 2 01 28 PM" src="https://user-images.githubusercontent.com/7014590/68997943-00c27e00-087a-11ea-9e91-64c56f11990b.png">

**Comment by howardm** [comment]
Ah, I see.

Thanks for the explanation.

Howard
