### ISSUE TITLE
Failure to get a text (text_spec) popover in Distill article using KableExtra

### ISSUE THREAD

**Issue by howardm** [haozhu233/kableExtra#442]
Hi,

This image shows the failure to see a Popover in a test sentence. (I'm hovering over the linked text.)
___
![Screen Shot 2019-11-24 at 11 10 46 AM](https://user-images.githubusercontent.com/6101226/69499067-a04fc400-0eab-11ea-851f-ffc140887a6c.jpg)
___

I have the following in my. Rmd file:

![Screen Shot 2019-11-24 at 11 15 52 AM](https://user-images.githubusercontent.com/6101226/69499082-d3925300-0eab-11ea-9fd2-fbc9534d6966.jpg)

____

Is there a discernible reason this is not working for me ?

Thanks.

**Comment by haozhu233** [comment]
popover and tooltip needs some js to run. R markdown comes with bootstrap.js so we have been relying on that. For distill, to get it work, you need to load additional js to distill. However the tricky part is that even after I added the requires js, it's still not working. It seems that the provided js didn't get passed to the document... I'm not sure where the bug is. Maybe distill but it's also possible that it's because I didn't get it done correctly or it's a rmarkdown bug. I would say this is kind of hard to fix right now.
