### ISSUE TITLE
kable & kable_styling print html style  to R console

### ISSUE THREAD

**Issue by dtdibaba** [haozhu233/kableExtra#448]
Hi Zhu:

When kable_styling is used with kable and format="html", it prints the html style to R console (not Rmarkdown); is this as a result of including current environment with the output? Can this be silenced? I had used sink("file") to silence in R console but this throws connection error if one wants to use the same code in Rmarkdown. 

Another question is, is that possible to add lines to thead ( like a solid line for the top and double for the bottom border) and a line to the lasttablerow? I tried the row_spec ( row, hline_after=TRUE) but it did not work for me.

I like the fact that multiple tables are browsable ( Previous/Next arrow) in R Viewer while using kable and kable_styling but could not work around the above issues.

**Comment by haozhu233** [comment]
@dtdibaba Are you using RStudio or some other IDE? The expected behavior should be that tables get printed to the notebook panel or the rstudio viewer (depending on your document setting) if you are using it interactively. If you knit the document, they will only go to your document. Anyway, I added an global option in #455. If you set `options(kableExtra_view_html = F)`, the browsable table behavior will be disabled. 

For your second question, you can use the newly added `kable_classic_2` to do that. Just use it as if you are using `kable_styling`. I will publish the latest version to CRAN in a few days.

**Comment by dtdibaba** [comment]
The issue I am talking about it is that in R Studio console, it prints the CSS style and data with <td> .....</td> and other similar tags to the console. The output in viewer is perfect.

Got it thank you!
Daniel
