### ISSUE TITLE
Linebreak cutting off row background color

### ISSUE THREAD

**Issue by datimmer** [haozhu233/kableExtra#452]
The background color for cells containing a linebreak are cut short (leaving a white space) if a cell in the same column has text longer than the cell with a linebreak. The issue is fixed if you specify a shorter column width, however, setting a column width won't work for my purposes. Any ideas on how to fix this, without specifying a column width? Thank you.

````
---
title: "Reproducible example"
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{fontspec}
---

```{r}
library(dplyr)
library(kableExtra)

data <- data.frame(c('1','2','3','4','5'),c('a','b','A long line with no break that makes the column long','Value that needs \n break'
                                    , 'another value that needs \n break'))
names(data) <- c('Column 1', 'Column 2')

data <- data %>% mutate_all(linebreak)
#subbing center alignment
data$`Column 2` <- gsub('[l]','[c]',data$`Column 2`, fixed = TRUE)

kable(data, 'latex', booktabs = T, linesep="", escape=F, align=c('l','c')) %>%
    kable_styling(position = 'left', latex_options = c('striped','scale_down'), font_size = 12)
```
````

**Comment by haozhu233** [comment]
@datimmer Yeah, I tried your example and this behavior is there. The problem is that latex tables are really not very friendly with self-specified newlines. When I was working on this, it seems that the best choice was to create a text box and do line break inside. With such a box, you will get this kind of coloring behavior. At the same time, it used to be okay when xcolor was still working but an update in another latex package caused a conflict and forced me to use another option. Anyway, given what I just said, I don't think this problem is fixable.

**Comment by datimmer** [comment]
All good, ended up going a different route regardless. Thank you for your response.

**Comment by preethirajasekaran** [comment]
@datimmer Facing the same difficulty. I need to scale_down the table because it has images and text, and needs to be in one single page. Tried inserting linebreaks manually so as to increase the font size despite the scale_down. What workaround did you go for?
