### ISSUE TITLE
kable with multiple outputs

### ISSUE THREAD

**Issue by MyKo101** [haozhu233/kableExtra#466]
I'm currently outputting multiple formats in `bookdown`. However, it seems that `kable` as exported from `kableExtra` cannot determine which output is being done when.

Consider the following .rmd (add the three backticks to the end, GH markdown won't keep them):
```
---
knit: (function(...) bookdown::render_book(...,output_format="all"))
#knit: bookdown::render_book
output:
  html_document: default
  pdf_document: default
---
```{r}
library(knitr)
#library(kableExtra)

kable(data.frame(x=rnorm(10),y=rnorm(10)))

cat("Output format: ",knitr:::opts_knit$get("out.format"),"\n",
    "HTML output: ",knitr:::is_html_output(),"\n",
    "LaTeX output: ", knitr:::is_latex_output(),
    "getOption(\"knitr.table.format\"): ",getOption("knitr.table.format")))

```
This will output a simple kable to both HTML and PDF.

Uncommenting the `library(kableExtra)` line causes neither table to render properly.

Looking at the HTML source and the tex file, it seems that it is outputting as a plain HTML table, but obviously this means that the tex file ignores the HTML tags.

It seems that the only way to render properly is to specify the format type to `kable()`, however the documentation says this will be automatically detected.

This _can_ be fixed by defining a function:
```
get_format <- function()
  if(knitr:::is_latex_output())
    "latex" else
      if(knitr:::is_html_output()) 
        "html" else "markdown"
```
and calling `kable()` as
```
kable(data.frame(x=rnorm(10),y=rnorm(10)),get_format)
```
(note that the `format` argument can be a function and does not need to be a function call.

The last line in the first code uses the command `getOption("knitr.table.format")`, which outputs as `html` for both HTML and PDF documents. This comes from the `kable()` function and is what is used to determine the format when nothing is provided.

I'm not sure why `kable()` behaves differently depending on whether it's been exported with `kableExtra` or not, but this is definitely a bug. I appreciate that this probably won't get fixed soon, but at least now this workaround is there for other's experiencing the same problem

**Comment by bastistician** [comment]
Thank you for the report. I just stumbled across the same bug.

If no format is specified, **knitr**`::kable` will first try `getOption("knitr.table.format")` and this is fixed when loading **kableExtra** (#424) here:

https://github.com/haozhu233/kableExtra/blob/9059e4bb189122fa30b456f5d2d6ca4b99f471bb/R/zzz.R#L22

So this output format will be used for the entire R session, i.e., all output formats of `render_site`.

Since **kableExtra** only applies to html or LaTeX "kables" anyway, one could set the appropriate format option manually:

```r
library(kableExtra)
options(knitr.table.format = if (knitr::is_latex_output()) "latex" else "html")
```

However, this isn't perfect as required LaTeX packages won't be loaded automatically (via **kableExtra**'s `.onLoad`) if LaTeX isn't the first output format.

A **workaround** is to call `render_site` for each output format separately.

**Comment by haozhu233** [comment]
@MyKo101 thanks for reporting and @bastistician thanks for your answer! What @bastistician said is correct. You may also want to read this doc https://haozhu233.github.io/kableExtra/bookdown/cross-format-tables-in-bookdown.html#use-the-k-m-approach-instead-of-m-k

**Comment by haozhu233** [comment]
@bastistician @MyKo101 Well, things get changed a little bit. I redefined a wrapper function for `kable` that does the environment check in every call. Although the main purpose is to provide detailed documentation for all the hidden arguments in `kable`, it should also solve this issue as a side effect.
