### ISSUE TITLE
kable_format %in% statement works wrong if kableExtra library not loaded

### ISSUE THREAD

**Issue by arencambre** [haozhu233/kableExtra#467]
Suppose you insert this code as a code block in an Rmd file, and further suppose you did not explicitly load the **kableExtra** library at any point:
```
library(tidyverse)

knitr::kable(
  mtcars[1:5, ], 
  caption = "A knitr kable."
) %>% kableExtra::kable_styling(bootstrap_options = "hover") 
```

Instead of a table with the Bootstrap hover effect, I get a table with no Bootstrap effect and the warning starting with "Please specify format in kable." It seems that these lines are misfiring: https://github.com/haozhu233/kableExtra/blob/9059e4bb189122fa30b456f5d2d6ca4b99f471bb/R/kable_styling.R#L114-L116

The resulting table opening tag is `<table>` and again has no Bootstrap refences.

I checked the attributes of the data being piped into the **kable_styling** function, and it shows a **format** attribute with value **html**. For some reason, that **html** value is not being seen by `kable_format %in% c("html", "latex")`.

If I add `library(kableExtra)`, the problem goes away.

Also, the preview produced in RStudio's Rmd editor and in the **Viewer** pane (bottom right) _do_ show the hover effect. Somehow the way those are knit doesn't cause that logic test to fail.

**Comment by haozhu233** [comment]
@arencambre This is an expected behavior. Both Rmarkdown and kableExtra are not as smart as they seem to be. In the past, you need to manually specify format in every kable call unless you use the not-widely-known global setting. In kableExtra 0.8 or 0.9, we start to set this option automatically based on the current rmarkdown environment and this step happens when this package gets loaded. That's why you need to load this package. ;)

**Comment by arencambre** [comment]
Thank you. Do you think a warning is possible?
