### ISSUE TITLE
striped latex overflow

### ISSUE THREAD

**Issue by MyKo101** [haozhu233/kableExtra#468]
Bit of a niche situation, but wanted to report since whatever is causing the problem might spread elsewhere. I only actually discovered this when I accidentally deleted my row names and the table wouldn't render.

When rendering a table with stripes, the stripe formatting (`\rowcolor{gray!6}`) can appear at the beginning of the table causing LaTeX to error: `\rowcolor{gray!6}  \begin{table}`

This *only* seems to happen when making a single column with no row names, ~~a user defined caption~~ and multiple blank rows in a row.

MWE:
```
tibble(x=c("0.01","","","0.03")) %>%
  kable(format="latex",
        booktabs=T,
        caption="test") %>%
  kable_styling(latex_options = "striped")
```

Output:
```
\rowcolor{gray!6}  \begin{table}

\caption{\label{tab:}test}
\centering
\begin{tabular}[t]{l}
\toprule
x\\
\midrule
\rowcolor{gray!6}  0.01\\
\\
\\
0.03\\
\bottomrule
\end{tabular}
\end{table}
```

Adding an extra column (even with blanks in place) removes the issue. Removing the caption moves the unexpected `\rowcolor{gray!6}` to the end of the `\centering` but the table still doesn't render.
Switching `booktabs` to `F` doesn't fixed the problem either (it just makes the output example shorter). Replacing the `""` entries with a space `" "` doesn't fix it, using non-blank entries (

The issue seems to be related to the duplicate rows, but that's as far as I've managed to track it down. If I have more time, I'll look into this in the future.

I have three solutions for now (for anybody else experiencing this unusual error:

* Add in row names or an extra column. Even if this makes your rows still identical having more than one column (since rownames are rendered as an extra column), this seems to fix it.

* Replacing the missing values with `NA`s and set `options(knitr.kable.NA = "")`

* Replacing the missing values with `\\quad` (note the double slash) and setting the `escape` argument to `FALSE` in `kable(...,escape=F)`

(Edit: user defined caption not necessary, table still doesn't render)

**Comment by haozhu233** [comment]
While this seems to be an easy issue, this problem is actually not fixable due the the mechanism of how this package works. Duplicated rows are really hard to deal with when you are using regex. The current solution is the best I can find. The only place it's not working is just as what you described - when there are duplicated rows and there is only one column. On some aspects, one column table are not really tables. They are more like a list. Based on this reasoning, I chose to let it go. :P

Anyway, thanks for raising this question and providing your thoughts and solutions!
