### ISSUE TITLE
Yellow Highlight a Row?

### ISSUE THREAD

**Issue by soleyjh** [haozhu233/kableExtra#48]
First off, this package is seriously amazing. Thank you so very much for building it.

Q: Is there a way to yellow highlight a row? it seems that row_spec() only allows for bold and italics?

**Comment by haozhu233** [comment]
A: There is a way with the dev version of this package. ;)

After devtools::install_github(), you can use things like
```
kable(...) %>%
  row_spec(background = "yellow")
```

I haven't put these things into documentation because of seriously lack of time recently (but I will). Please feel free to try it out. Also you can change font color with the option `color`.

**Comment by soleyjh** [comment]
Thanks man!
