### ISSUE TITLE
let landscape() cache (or warn) \usepackage{lscape} \usepackage{pdflscape} insertions

### ISSUE THREAD

**Issue by maxheld83** [haozhu233/kableExtra#51]
I'm a happy user of `landscape()`, but I ran into a slight snafu on repeated builds with cache, and I have a theory as to why this happened.

**Observation**

*Only* on cached (via knitr) compilations, the LaTeX compilation would fail with something like `landscape environment undefined`.

Deleting the cache, or setting the chunk with `landscape()` option `cache = FALSE` resolved the problem.

Our project, at this point, had no `\usepackage{lscape}`or `\usepackage{pdflscape}` in its `preamble.tex`.

**Hypothesis**

I am assuming that when `landscape()` is called, `kableExtra` does some black magic to insert the necessary `usepackage{lscape}` and friends into the preamble.
This, however, would be a *side effect* that wouldn't (couldn't) be cached.
Whenever the offending chunk is unchanged, a repeated run will leave the chunk *unevaluated* and `knitr` will simply reuse the old outputs, of course *without* the side effects.

On all `n>=1` runs without changed chunks, then, black magic never happens and `\usepackage{lscape}` and friends are never appended, causing a failed compilation.

**Solution**

I don't know, I like the idea of not manually calling `usepackage{lscape}`, but these side effects are thorny to debug.
This may be hard for other users to recognise (I have some painful experience with caching).

Perhaps warn users about this, or simply *not* do the black magic, but ask users to manually add the packages?

(cc @VerenaKasztantowicz)

**Comment by haozhu233** [comment]
Ach, I totally didn't expect having cache could have such an effect... Thanks for bringing it up!

Your hypothesis is correct. `landscape()` will ask rmarkdown to put `\usepackage{pdflscape}` in the header when it's called. It is done through the `usepackage_latex()` function in this package. If you use TeX a lot, you will probably like this utility function. ;)

For the solution, as mentioned in #46, one thing on the top of my to-do list is to complete the documentation with a list of LaTeX packages that kableExtra loads automatically and some suggestions on when you should load these packages  by yourself. I bet that will help advanced TeX users a lot in the future.

**Comment by haozhu233** [comment]
Hi, @maxheld83, 

Thanks again for raising this issue. So far I did 2 things to improve this feature here. 

1. In the past, LaTeX package `pdflscape` won't be loaded until `landscape()` was called. That's why when the chunk results were saved, only this feature won't work. Now, I move the location of "black magic trigger" to the start of this package, which should be loaded in most cases. I think it should solve the problem in most cases.

2. I also provided documentation about the "black magic" and put it at the very beginning of the pdf vignette, which you can have a look here http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf. 

3. Now you can also suppress the "black magic" via a global option before you load this package. You can see the vignette for details.
