### ISSUE TITLE
how to remove begin{tabular} ?

### ISSUE THREAD

**Issue by randomgambit** [haozhu233/kableExtra#52]
Hello,

thanks for this amazing package. 

I use it to export dataframes to latex tables that I can include in my tex. However, I was unable to only get the `fragment` of the table, that is the latex output **without** the `\begin{tabular}` environment (because I use my own). 

Is there a way to get rid of these lines using `kableExtra` ?

Thanks!

**Comment by haozhu233** [comment]
Hi, @randomgambit, is this the same issue as #53? Is `tabularx` just the string you need?

**Comment by randomgambit** [comment]
@haozhu233 this is actually a different issue. 

This is more to provide some sort of `fragment` option similar to `esttab` in Stata http://repec.org/bocode/e/estout/hlp_esttab.html 

>  fragment           suppress table opening and closing (LaTeX, HTML)

I found a way to remove the top and bottom lines of the output, but this feels a bit hacky to me.

**Comment by haozhu233** [comment]
I would be a little hesitate on adding this feature because what if you provide a caption and `kable` put ur table into a floating `table` shell. In that case removing `tabular` seems quite problematic. 

If you look into the source of kableExtra, you may feel some latex parts are pretty hacky as well. So don't be afraid to be a hacker. :P

**Comment by randomgambit** [comment]
@haozhu233 okidoki :) IMHO the most important feature would be to have a `tabularx` env option ;-) Thanks!!

**Comment by 1beb** [comment]
You can post process your tex: 

```
tx = readLines("my.tex")
tx = gsub("tabular", "tabularx")
write(tx, file="my.tex")
```
