### ISSUE TITLE
Repeating add_header_above

### ISSUE THREAD

**Issue by sgummidipundi** [haozhu233/kableExtra#520]
Kable has been great when I'm repeating column headers on multiple pages for a very long table. Is there any way that I can also repeat the grouping headers generated by add_header_above()?

Thank you in advance!

**Comment by haozhu233** [comment]
You can just put `add_header_above` before `kable_styling`

```
library(kableExtra)

rbind(mtcars[1:3],mtcars[1:3],mtcars[1:3],mtcars[1:3]) %>%
  kbl(booktabs = T, longtable = T) %>%
  add_header_above(c(" " = 1, "aaa" = 3)) %>%
  kable_styling(latex_options = "repeat_header")
```

**Comment by JoseCarlosMartinez** [comment]
Thank you for your great work.

The problem is solved for a latex output, however, for html, the added header does not maintain its initial position. It is fixed but below the column names.

![header](https://user-images.githubusercontent.com/37913889/124199402-1928f000-dad3-11eb-9781-9093b408e6b0.png)

![header_fixed](https://user-images.githubusercontent.com/37913889/124199410-1f1ed100-dad3-11eb-9617-20fc73cd9a7e.png)
