### ISSUE TITLE
Save SVG files from `spec_hist`, `spec_boxplot`, `spec_line`

### ISSUE THREAD

**Issue by vincentarelbundock** [haozhu233/kableExtra#526]
Hi,

I’m loving the mini-plots.

I would like to save a LaTeX table with histograms for later use. Right now, my problem is that there does not seem to be a way to save the SVG files, because SVGs are deleted automatically.

One possibility would be to modify those three lines of code to `unlink` only if `dir` was not specified explicitly by the user. 

https://github.com/haozhu233/kableExtra/blob/master/R/mini_plots.R#L82
https://github.com/haozhu233/kableExtra/blob/master/R/mini_plots.R#L199
https://github.com/haozhu233/kableExtra/blob/master/R/mini_plots.R#L359

That way we could specify a directory to store SVG files, and those could be used for LaTeX compilation at a later stage.

What do you think?

```r
library(kableExtra)

mpg_list <- split(mtcars$mpg, mtcars$cyl)
inline_plot <- data.frame(cyl = c(4, 6, 8), mpg_box = "", mpg_hist = "")
inline_plot %>% 
  kbl(booktabs = T) %>%
  kable_paper(full_width = F) %>%
  column_spec(2, image = spec_boxplot(mpg_list, dir="test_hist")) %>%
  column_spec(3, image = spec_hist(mpg_list, dir="test_box"))
```

**Comment by haozhu233** [comment]
Yep, svg files are deleted automatically because I was hoping to get a clean exit for in-console real time rendering of html tables. Right now, the content of the svg files are saved under `svg_text`. If you really need them, I guess you can cat them into files?

```
svg_plots <- kableExtra::spec_boxplot(mpg_list, dir="test_hist")
cat(svg_plots[[1]]$svg_text, "1.svg")
```

In another thread, we are actually talking about using `pdf` and other formats, which provides better resolution. https://github.com/haozhu233/kableExtra/issues/524. In fact, once we have that implemented, it's better to use pdf instead of svg in latex cuz for latex you need an extra svg package to load svg files.

**Comment by vincentarelbundock** [comment]
Great thanks. I'll watch the other thread as I'm very interested in those development.

As always, thanks for all your work on this!
