### ISSUE TITLE
kable styling to pdf with cellcolor using package tabu

### ISSUE THREAD

**Issue by zahlenzauber** [haozhu233/kableExtra#597]
When rendering to pdf kableExtra relies on package tabu. Unfortunately, this package is not maintained on a regular basis anymore (see http://mirrors.ctan.org/macros/latex/contrib/tabu/README.md). 
Most things are still working. Coloring of cells does not (see https://github.com/tabu-issues-for-future-maintainer/tabu/issues/13).

Maybe, xltabular is an alternative approach (https://www.ctan.org/pkg/xltabular).

**Comment by haozhu233** [comment]
Well, not quite. In most cases, kableExtra only puts a table in the `tabu` environment when you set `full_width` to be True. If `full_width = F`, the output will be a regular tabular table. I chose to use `tabu` because it was the only environment that supports a full-width table with a fairly good accuracy based on my research at that time.

**Comment by zahlenzauber** [comment]
Thank you for the explanation (and the package by the way). This solved my issue.
