### ISSUE TITLE
Decimal point alignment

### ISSUE THREAD

**Issue by ashgreat** [haozhu233/kableExtra#61]
Can you please add aligning numbers in a column based on decimal point? LATEX has a nice package names siunitx that can handle this easily. This link provides an example:
https://tex.stackexchange.com/questions/2746/aligning-numbers-by-decimal-points-in-table-columns

I have not come across any package in R that allows this.

**Comment by wibeasley** [comment]
@ashgreat, would this help in the meantime?  Use a monospace font and [`sprintf()`](https://www.rdocumentation.org/packages/base/versions/3.4.1/topics/sprintf) to [pad right](https://stackoverflow.com/a/9262031/1082435) (with spaces or zeros)?

**Comment by ashgreat** [comment]
The problem with that usually is that we use "*" to indicate significance of the coefficients and these are attached the numbers. For example, a coefficient 0.567 that's significant at 1% level might be written as 0.567***. Some other coefficient 0.123 that's significant at 5% will be written as 0.123**. Thus, the length of each value is different. Mono space fonts won't be useful here.
Take a look at this for example. This is done in Word, which has pretty straightforward way of doing it. https://imgur.com/a/hI0kS

**Comment by wibeasley** [comment]
@ashgreat, I gotcha.  I'm familiar with the feature in Word.

I think I understand now.  It sounds like you aren't feeding kableExtra a number like `0.123`.  You're feeding receiving a string like `"0.123`" or "`0.123***`", therefore sprintf can't tell the difference between the last digits and any asterisks.  Does this solve your immediate needs?

```r
library(magrittr)
s <- c("0.123**", "0.123", "0.123*", "0.123****")

asterisk_count <- gregexpr("\\*", s) %>% 
  purrr::map(~attr(., "match.length") > 0L) %>% 
  purrr::map_int(~sum(.)) 

asterisk_count_max <- max(asterisk_count)

spaces_to_add <- asterisk_count_max - asterisk_count

spaces <- spaces_to_add %>% 
  purrr::map(~rep(" ", times=.)) %>% 
  purrr::map_chr(~paste(., collapse=""))

padded <- paste0(s, spaces)
padded
```

```r
[1] "0.123**  " "0.123    " "0.123*   " "0.123****"
```

**Comment by haozhu233** [comment]
@wibeasley Thank you so much for providing a solution!

@ashgreat Nice suggestion! In fact, this is a feature I really want to have as well. The difficult part is that due to my lack of knowledge in LaTeX, I feel like the `S` column type has its unique way of defining column width (https://tex.stackexchange.com/questions/350439/reducing-siunitx-column-width) and I'm not sure if features like bold/italic could be fulfilled at the same time. For HTML, it's also very complicated and requires this package to be a htmlwidget (good thing is that this is on the plan). 

I guess I should take more time and do some more exploration. If you know how to get it done, let me know and I would appreciate that. :)

**Comment by randomgambit** [comment]
hello there @haozhu233 ! any news regarding how to properly add significance stars to a `kableExtra` output (latex) ? is the solution proposed by @wibeasley still the state of the art? thanks!!

**Comment by haozhu233** [comment]
@randomgambit I would say yes? I mean I can try to integrate a similar workflow into kableExtra but I'm  not sure if there is a solution for other similar cases.
