### ISSUE TITLE
save_kable() saves .tex with ANSI encoding; expecting UTF-8

### ISSUE THREAD

**Issue by tomasrei** [haozhu233/kableExtra#685]
**Describe the bug**

save_kable() saves .tex files with ANSI encoding; expecting UTF-8

reprex:
````
library(tidyverse)
library(kableExtra)

test <- lm(mpg ~ cyl + wt, mtcars) %>% tidy() %>%
  kbl(format = "latex") %>% 
  footnote(number = c("Testa  å ä ö"))

save_kable(test, file = "plain.tex")

````
The problem is that when I convert the .tex file to pdf using pandoc, It won't work because the encoding is wrong. I will get an error like:
````
Invalid UTF-8 byte sequence (´┐¢´┐¢´┐¢).
````
If I open the .tex file in notepad and re-save it with UTF-8, it will work. However, this is tedious, as I modify my tables a lot before it is finished.

EDIT:
I found one kind of hacky solution:
````
writeLines(test, file('test.tex', encoding = 'UTF-8'))
````

But there must be a better way?

**Comment by dmurdoch** [comment]
I think kableExtra will save the text of `test` in whatever encoding it receives.  If you're working on a machine where the native encoding is not UTF-8, then you will probably need to convert `test` to a UTF-8 encoding before saving, e.g.

    save_kable(enc2utf8(test), file = "plain.tex")

I don't think this could be the default way to save, because other users on non-UTF8 machines will want to save in the native encoding, or will get errors.
