### ISSUE TITLE
Blank table in Rmarkdown inline rendering with dark-themed Rstudio

### ISSUE THREAD

**Issue by matthewgson** [haozhu233/kableExtra#689]
Hi, I'm having an issue exactly described here : 
https://github.com/vincentarelbundock/modelsummary/issues/269

The author seems to have solved the issue by using `kable()` instead of `kbl()`, but forgot to raise it here.

**Comment by zaynesember** [comment]
Also have been having this issue. So frustrating!

**Comment by andrewheiss** [comment]
This continues to be an issue, but there's a temporary workaround [here](https://stackoverflow.com/a/71771178/120898). You can inject `color: black;` into the inline CSS for the kableExtra table by modifying the existing `print.kableExtra()` function:

```r
print.kableExtra <- function (x, ...) {
  view_html <- getOption("kableExtra_view_html", TRUE)
  if (view_html & interactive()) {
    dep <- list(
      rmarkdown::html_dependency_jquery(), 
      rmarkdown::html_dependency_bootstrap(theme = "cosmo"), 
      kableExtra::html_dependency_kePrint(), 
      kableExtra::html_dependency_lightable()
    )
    
    x <- sub('style="', 'style="color: black; ', as.character(x), fixed = TRUE)
        
    html_kable <- htmltools::browsable(
      htmltools::HTML(
        as.character(x), 
        "<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {inlineMath: [[\"$\",\"$\"]]}})</script><script async src=\"https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>"
      )
    )
    htmltools::htmlDependencies(html_kable) <- dep
    class(html_kable) <- "shiny.tag.list"
    print(html_kable)
  }
  else {
    cat(as.character(x))
  }
}
``` 

This fixes things when working with a dark theme.

Before (using the Monokai theme in RStudio):

<img width="875" alt="image" src="https://user-images.githubusercontent.com/73663/176480293-b73e61d4-b0f7-4c52-b8a5-c29f80561f9e.png">

After running new `print.kableExtra()` (again, with the Monokai theme):

<img width="870" alt="image" src="https://user-images.githubusercontent.com/73663/176480205-4978e3bd-3a70-4d76-9e19-8638670c499c.png">

You can include the new `print.kableExtra()` in ~/.Rprofile so that you have access to it in every new R session (though it'll show up in the environment and clutter it up 🤷‍♂️)

This is a good temporary solution, but it would be cool to someday have `style="color: black;"` automatically built in

**Comment by andrewheiss** [comment]
@haozhu233 Would adding `x <- sub('style="', 'style="color: black; ', as.character(x), fixed = TRUE)` to line 11 in `print.kableExtra()` here… 

https://github.com/haozhu233/kableExtra/blob/a6af5c067c2b4ca8317736f4a3e6c0f7db508fef/R/print.R#L2-L23

…mess things up in light themes or other non-RStudio editors, or would that be a safe change? I'd be happy to open a PR if it's safe.

Thanks!

**Comment by vincentarelbundock** [comment]
FWIW, I think a "cleaner" fix would be to add this code [on line 267 of `kable_styling.R`](https://github.com/haozhu233/kableExtra/blob/master/R/kable_styling.R#L267)

```r
  # issue 689: invisible font in Rstudio dark theme
  flag <- tryCatch(rstudioapi::getThemeInfo()$dark, error = function(e) FALSE)
  if (isTRUE(flag)) {
    kable_xml_style <- c(kable_xml_style, "color: black;")
  }
```

I'd be curious if anyone could try it and let me know if it works on their computer as well. You can try my fork by calling:

```r
remotes::install_github("vincentarelbundock/kableExtra@dev")
```

Restart R completely, and try again.

**Comment by vincentarelbundock** [comment]
Fixed here: https://github.com/haozhu233/kableExtra/pull/768
