### ISSUE TITLE
collapse_rows not working

### ISSUE THREAD

**Issue by 4daren** [haozhu233/kableExtra#706]
Hello,

I was directed here from RStudio Community

When I try to use collapse_rows I get no effect - can't locate fault in the code, it is:
```{r}
library(kable)
library(kableExtra)

mtcars <- arrange(mtcars, cyl)
kbl(mtcars) |> kable_classic(full_width=F) |> collapse_rows(columns = 2, valign = "top")
```

PS Thanks for the great stuff kableExtra is :)

**Comment by cderv** [comment]
For reference, this comes from RStudio Community: https://community.rstudio.com/t/kableextra-collapse-rows-not-working-reason-unknown/134721/12

**Comment by haozhu233** [comment]
Hi, @4daren and @cderv, I think this problem is fixed in the github version but I just haven't made a CRAN release for a long time. I will try to get it updated in the next couple of days. 

@4daren You can install the github version if you need. 

Also, in your code, you need

```
library(kableExtra)

mtcars <- arrange(mtcars, cyl)
kbl(mtcars) |> kable_classic(full_width=F) |> collapse_rows(columns = 3, valign = "top")
```

because cyl is in the 3rd column (now the first column is the row names)

**Comment by 4daren** [comment]
Great, thanks ;)

**Comment by 4daren** [comment]
Great, thanks ;)

**Comment by Martin-Venegas-M** [comment]
Hi! to this date I have the same problem. `collapse_rows()` is not working and I already update the `kableExtra()` version with the commit `a6af5c0`.

Any suggestions?

**Comment by kristian-bak** [comment]
@Martin-Venegas-M : I had the same issue with kableExtra v1.3.4.9000. Updating rvest to v1.0.3 fixed it for me. @haozhu233: perhaps min_version is needed for rvest in the DESCRIPTION file.
