### ISSUE TITLE
permit negative indexes on row_spec and column_spec

### ISSUE THREAD

**Issue by mgacc0** [haozhu233/kableExtra#741]
Would you consider of interest implementing the possibility of specifying negative indexes on the row number of `row_spec` (and also on the column number of `column_spec`)?
It is very common needing to apply a certain format to the last row. And it would be easier if we could write `row_spec(-1, ...)`.

**Comment by dmurdoch** [comment]
In R, an index of -1 generally means every entry except number one, so I'd expect that to mean all rows except the first.

**Comment by krivit** [comment]
Up until 989d6dc7531b01bd47b609ae7585f1726fb0743d, `row_spec(-1, ...)` would affect the first row of a two-row header. However, this does not appear to have been intended functionality but rather a serendipitous (if useful, IMO) feature.

Since 989d6dc7531b01bd47b609ae7585f1726fb0743d, it just produces an error.

**Comment by dmurdoch** [comment]
I think the proposal in #827 makes more sense in R than this one, so I'm going to close this issue.
