### ISSUE TITLE
Problems with output of tables containing multibyte characters

### ISSUE THREAD

**Issue by ujtwr** [haozhu233/kableExtra#821]
**Describe the bug**

When a table containing multibyte characters is output with the kable() and kable_styling() functions, some characters are substituted into the pipe and disrupted.

**To Reproduce**

1. No multibyte characters are included (No problem)

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)

tibble(
  col1 = c("aaa", "bbb", "ccc"),
  col2 = c(123, 456, 789)
) %>% 
  kable( ) %>% 
  kable_styling()
```
![image](https://github.com/haozhu233/kableExtra/assets/42717412/806e9717-cf0f-4bea-82a1-598e0baa5d19)

2. Multibyte characters are included and only the kable function is used (No problem)

```{r}
tibble(
  col1 = c("あいう", "えお", "かきく"),
  col2 = c(123, 456, 789)
) %>% 
  kable()
```
![image](https://github.com/haozhu233/kableExtra/assets/42717412/db46a976-ac38-482c-805e-8fa8cfcf9b67)

3. Multibyte characters are included and the kable function and kable_styling function are used (problem arises)

```{r}
tibble(
  col1 = c("あいう", "えお", "かきく"),
  col2 = c(123, 456, 789)
) %>% 
  kable() %>% 
  kable_styling()
```
![image](https://github.com/haozhu233/kableExtra/assets/42717412/edf71402-60f6-4092-81d3-ad942cf0e00c)

The pipe symbol is placed at the end of the string in each columns. And the first number in the second column is missing.

4. Multibyte characters are included and the kable function and kable_styling function are used, but specify the format option to the kable function (No problem)

```{r}
tibble(
  col1 = c("あいう", "えお", "かきく"),
  col2 = c(123, 456, 789)
) %>% 
  kable(
    format = "html"
  ) %>% 
  kable_styling()
```
![image](https://github.com/haozhu233/kableExtra/assets/42717412/4f0e6840-07e8-4462-95d6-2271f2a0ecee)

5. Format option to the kable function is "latex" (No problem)

```{r}
tibble(
  col1 = c("あいう", "えお", "かきく"),
  col2 = c(123, 456, 789)
) %>% 
  kable(
    format = "latex"
  ) %>% 
  kable_styling()
```
```latex
\begin{table}
\centering
\begin{tabular}{l|r}
\hline
col1 & col2\\
\hline
あいう & 123\\
\hline
えお & 456\\
\hline
かきく & 789\\
\hline
\end{tabular}
\end{table}
```
5. Format option to the kable function is "pipe" (problem arises)

```{r}
tibble(
  col1 = c("あいう", "えお", "かきく"),
  col2 = c(123, 456, 789)
) %>% 
  kable(
    format = "pipe"
  ) %>% 
  kable_styling()
```
![image](https://github.com/haozhu233/kableExtra/assets/42717412/87909b28-1f4e-4efd-9a7f-806d522c9b97)

The same phenomenon occurs. Is this a problem when the "pipe" is specified as the format option in the kable function? 

6. Use kbl() function instead of kable with kable_styleying (No problem)

```{r}
tibble(
  col1 = c("あいう", "えお", "かきく"),
  col2 = c(123, 456, 789)
) %>% 
  kbl() %>% 
  kable_styling()
```
![image](https://github.com/haozhu233/kableExtra/assets/42717412/5f8f56ec-c56b-4383-a67d-deb3695e6ca5)

**Comment by dmurdoch** [comment]
`kable()` isn't defined in `kableExtra`, it's just imported from `knitr` and exported without changes.  So really only the cases where `kbl()` was used belong here, but in fact `kbl(format = "pipe")` shows the same problem.

What happens is that `kable_styling()` needs to convert the pipe table to either HTML or LaTeX.  It chooses HTML by default, but something is causing `kableExtra:::md_table_parser()` to leave the pipe symbols in place.

After some debugging, it looks like the issue is a bug in `md_table_parser()`.  It assumes that the pipe symbols separating columns are always at the same character position in the input table, as they normally are with ASCII characters.  But the hiragana characters are double width, so `kable()` puts the pipe characters at varying positions to make the pipe table look better.  When `kable_styling()` processes that input, it gets the column break locations wrong.

**Comment by dmurdoch** [comment]
I think the PR I just submitted will fix this.  You can use it by installing the devel version and making sure you get version 1.4.0.3 or higher. 

If you can't do that, you could avoid the problem by avoiding pipe format tables.  By default `kbl()` doesn't produce them, so stick to `kbl()` and you should be fine.
