### ISSUE TITLE
add_footnote doesn't support full width i.e. tabu tables

### ISSUE THREAD

**Issue by nichtleiter** [haozhu233/kableExtra#88]
Hey,

there is another feature missing due to the inconsistent implementation of full width and non-full width tables (see #79 for another example).

`add_footnote` is not able to handle tables in a `tabu` environment. It's more than a missing feature rather a bug since the code for the `tabu`-case is missing in `add_footnote.R`.

I will work on an implementation with `threeparttablex`. This will also work with long tables.

Again the question is raised whether it's more reasonable to switch the whole design to `tabu` tables. The code would be pretty messy if future features have to be always implemented for the `tabu` and `tabular` case.

But it's the same old question: Does kableExtra align with the minimalist or the consistency paradigma :)

Best regards

**Comment by haozhu233** [comment]
If you have ever tried to admin rstudio connect/server on a centOS you will know why I don't want to move to tabu...

In short, the texlive distribution on centOS lacks many important latex packages including tabu. What makes things worse is that the centOS texlive doesn't come with a latex package manager so that's almost like a game over. The solution I found is that you have to install the vanilla version of the TUG distribution to get everything work but that's kind of complicated and is not documented in the official guide. That's why in this package, I was trying to use as few latex packages as possible to achieve the desired results. Same logic goes with threeparttable. I know threeparttable usually gives you better result with footnotes but in current design, you have to turn it on to use it.
