### ISSUE TITLE
kableExtra problem on Linux server

### ISSUE THREAD

**Issue by vrybkin** [haozhu233/kableExtra#93]
Hi Hao,

Many thanks for this package. I've been having trouble using this package on a Linux server, and I suspect the issue is related to the XML dependency of this package but I am not entirely sure. For example, if you have a kableExtra table that is changed by a check box button, sometimes the table crashes and other times it works with no other changes in inputs. I'd say 80% of the time the table crashes, and 20% of the time it renders. If I do not use the kableExtra package, the table behavior is completely normal under the same circumstances. Do you have any hints as to what may be going on? The package itself installs just fine in the Linux environment, and this described functionality runs without a problem on my Windows machine. It's just in the Linux based environment where it has very inconsistent behavior.

Thank you for your time!

**Comment by haozhu233** [comment]
Which linux system are you using? I also installed this package in the rstudio server & connect at my workplace on CentOS and they seem to work fine. 

Since you mentioned this package was installed correctly, I assume you have `libxml2-dev` (system dependency of xml2) installed correctly? Maybe you can try to reinstall that?

If you have a reproducible example, maybe you can send it to me via email?
